backend/urls.py
from django.conf.urls import patterns, include, url
# handle static files locally
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import cache_page
from backend.views import get_kmap_browser_view, get_search_view, get_landing_page

"""
Django urls handler. Valid URLS/Requests:
  kmap(s)                           display knowledge-map browser

see backend/simple_server for valid content requests
"""

urlpatterns = patterns('',
                       (r'^$', get_landing_page),
                       (r'^(?i)kmaps?/', get_kmap_browser_view),
                       (r'^(?i)search', get_search_view)
)

urlpatterns += staticfiles_urlpatterns()

server/apps/user_management/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.views.generic.base import TemplateView
from apps.user_management import views
from apps.user_management.models import UserCreateForm as Form

urlpatterns = patterns('',
                       url(r'^$', views.user_main, name='user_main'),
                       url(r'^login$', login, {'template_name': 'user_management/login.html'}, name='login'),
                       url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
                       url(r'^register$', views.register, name='register'),
                       url(r'^password_reset$', password_reset,
                           {'template_name': 'user_management/password_reset_form.html',
                            'email_template_name': 'user_management/password_reset_email.html',
                            'subject_template_name': 'user_management/password_reset_subject.txt',
                            'post_reset_redirect': "/user/password_reset/sent"}, name='password_reset'),
                       url('^password_reset/sent$', password_reset_complete,
                           {'template_name': "user_management/password_reset_complete.html"}, name="password_reset_complete"),
                       url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                           password_reset_confirm, {'template_name': 'user_management/password_reset_confirm.html',
                                                    'post_reset_redirect': '/user/password_reset/success'}, name="password_reset_confirm"),
                       url(r'^password_reset/success$', password_reset_done,
                           {'template_name': 'user_management/password_reset_done.html'}, name='password_reset_done'),
                       url(r'^concepts/([^/]*)$', views.handle_concepts)
                       )

server/urls.py
import pdb
from django.conf.urls import patterns, include, url
# handle static files locally
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView, RedirectView
from haystack.views import search_view_factory
from haystack.query import SearchQuerySet

from apps.roadmaps import views as roadmap_views

from views import MultiSearchView, ContactView, get_list_view, get_browsing_view, autocomplete

admin.autodiscover()

sqs = SearchQuerySet().filter(is_listed_in_main_str="True")
sqs.order_by('score')
search_inst = search_view_factory(view_class=MultiSearchView, searchqueryset=sqs, template='search-results.html')

"""
Django urls handler
"""
urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(template_name="landing.html")),
                       url(r'^(?i)autocomplete/?$', autocomplete, name="autocomplete"),
                       url(r'^(?i)search$', search_inst, name="haystack_search"),
                       url(r'^(?i)list$', get_list_view),
                       url(r'^(?i)browse$', get_browsing_view),
                       url(r'^(?i)concepts/((?P<anything>.*))',
                           RedirectView.as_view(url="/graphs/concepts/%(anything)s", query_string=True), name='concepts'),
                       url(r'^(?i)graphs/', include('apps.graph.urls', namespace="graphs") ),
                       url(r'^user/', include('apps.user_management.urls', namespace='user') ),
                       url(r'^roadmaps/', include('apps.roadmaps.urls', namespace='roadmaps')),
                       url(r'^course_guides/', roadmap_views.course_guide_list),
                       url(r'^captcha/', include('captcha.urls')),
                       url(r'^about/?$', TemplateView.as_view(template_name='about.html')),
                       url(r'^terms/?$', TemplateView.as_view(template_name='terms_of_service.html'), name="terms"),
                       url(r'^feedback/?$', ContactView.as_view()),
                       url(r'^thanks/?$', TemplateView.as_view(template_name='feedback_thanks.html')),
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^browser-tests', include('apps.browser_tests.urls', namespace="btests")),
)

urlpatterns += staticfiles_urlpatterns()

server/apps/user_management/models.py
import pdb

from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email

from captcha.fields import CaptchaField

class UserCreateForm(UserCreationForm):
    email = forms.CharField(validators=[validate_email],
        error_messages={'invalid': ('Please enter a valid email address.')})
    captcha = CaptchaField()
    tou = forms.BooleanField(initial=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "captcha", "tou")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean_tou(self):
        tou = self.cleaned_data["tou"]
        if not tou:
            raise forms.ValidationError("You must agree to our terms of use.")

    def clean_email(self):
        email = self.cleaned_data["email"]
        if len(User.objects.filter(email=email)) > 0:
            raise forms.ValidationError("This email address is already registered to an account -- use the username/password reminder (below) to obtain the credentials for this email.")
        return email

    def get_credentials(self):
        return {
            'username': self.cleaned_data['username'],
            'password': self.cleaned_data['password1']}

class Profile(models.Model):
    """
    This is a skeleton user profile model with a one-to-one relationship
    with users from the auth model

    The profile was originally conceived to allow easy future extension of the user model without dealing with messy schema changes
    """
    user = models.OneToOneField(User, primary_key=True)

    def __unicode__(self):
        return self.user.username

# FIXME WE NEED TO REMOVE THIS MODEL
class Concepts(models.Model):
    learned_uprofs = models.ManyToManyField(Profile, related_name="learned")
    starred_uprofs = models.ManyToManyField(Profile, related_name="starred")
    id = models.CharField(max_length=10, unique=True, primary_key=True)

server/apps/user_management/views.py
import json
import pdb

from django.shortcuts import render_to_response, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.shortcuts import render
from apps.user_management.models import Profile, UserCreateForm
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import authenticate, login

from lazysignup.decorators import allow_lazy_user
from lazysignup.templatetags.lazysignup_tags import is_lazy_user
from lazysignup.models import LazyUser

from apps.graph.models import Concept
from aux_text import HTML_ACCT_EMAIL, TXT_ACCT_EMAIL


def user_main(request):
    if not request.user.is_authenticated() or is_lazy_user(request.user):
        return redirect('/user/login?next=%s' % request.path)

    uprof, created = Profile.objects.get_or_create(pk=request.user.pk)

    # list graphs they've edited
    graphs = [gs.graph for gs in uprof.edited_graph.all()]

    # list concepts they've edited
    concepts = [cs.concept for cs in uprof.edited_concept.all()]

    # list roadmaps where the user is listed as an owner
    roadmaps = [rs.roadmap for rs in uprof.roadmap_owners.all()]

    # obtain an array of learned concept ids for the user
    lids = [l.id for l in uprof.learned_concepts.all()]
    sids = [s.id for s in uprof.starred_concepts.all()]

    # FIXME TODO refactor and use the new database
    if len(lids) > 0:
        lconcepts  = [Concept.objects.get(id=idval) for idval in lids if Concept.objects.filter(id=idval).exists()]
    else:
        lconcepts = []

    if len(sids) > 0:
        sconcepts  =  [Concept.objects.get(id=idval) for idval in sids if Concept.objects.filter(id=idval).exists()]
    else:
        sconcepts = []

    return render_to_response('user_management/user.html',
                              {
                                  "lconcepts": lconcepts,
                                  "sconcepts": sconcepts,
                                  "roadmaps": roadmaps,
                                  "graphs": graphs,
                                  "concepts": concepts
                              },
                              context_instance=RequestContext(request))

@allow_lazy_user
def register(request, redirect_addr="/user"):

    # don't allow logged-in users to register a new account
    if request.user.is_authenticated and not is_lazy_user(request.user):
        return HttpResponseRedirect(redirect_addr)

    if request.method == 'POST':
        form = UserCreateForm(request.POST, instance=request.user)

        if form.is_valid():

            # save lazy or non-lazy acct
            if is_lazy_user(form.instance):
                user = LazyUser.objects.convert(form)
            else:
                user = form.save()

            # create and save corresponding profile
            prof = Profile(user=user)
            prof.save()

            # send basic info email
            uname = form.cleaned_data['username']
            subject, from_email, to = 'Metacademy account successfully created', 'accounts@metacademy.org', form.cleaned_data['email']
            text_content = TXT_ACCT_EMAIL % uname

            html_content = HTML_ACCT_EMAIL % uname
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")

            try:
                msg.send()
            except:
                # TODO handle incorrect emails better
                print "Unable to send confirmation message to " + to
            login(request, authenticate(**form.get_credentials()))
            return HttpResponseRedirect(redirect_addr)
    else:
        form = UserCreateForm()
    return render(request, "user_management/register.html", {
        'form': form,
    })

# we may want to consider using a more structured approach like tastypi as we
# increase the complexity of the project
# or maybe just switching to class-based views would simplify this makeshift API
@allow_lazy_user
def handle_concepts(request, cid=""):
    """
    A simple interface for handling a user's association with a concept
    """
    rbody = json.loads(request.body) # communication payload
    method = request.method

    if method == "PUT":
        if not cid:
            cid = rbody["id"]
        learned = rbody["learned"]
        starred = rbody["starred"]

        uprof, created = Profile.objects.get_or_create(pk=request.user.pk)
        concept_obj, ucreated = Concept.objects.get_or_create(id=cid)

        if learned:
            uprof.learned_concepts.add(concept_obj)
        else:
            uprof.learned_concepts.remove(concept_obj)
        if starred:
            uprof.starred_concepts.add(concept_obj)
        else:
            uprof.starred_concepts.remove(concept_obj)

        hresp = HttpResponse(status=200)
        return hresp
    else:
        return HttpResponse(status=405)

server/apps/user_management/templates/user_management/login.html
{% extends "base_form.html" %}

{% block form-content %}
<div class="user-form-field">
  {{ form.username.label_tag }}
  {{ form.username }}
  {% if form.username.errors %}
  <div class="form-errors">
    {{form.username.errors}}
  </div>
  {% endif %}
</div>

<div class="user-form-field">
  {{ form.password.label_tag }}
  {{ form.password }}
  {% if form.password.errors %}
  <div class="form-errors">
    {{form.password.errors}}
  </div>
  {% endif %}

</div>
{% endblock %}

{% block button-text %}"login"{% endblock %}

{% block post-form-text %}
<div class="forgot-pw-link">
     <a href="{% url "user:register" %}">create an account</a>
</div>
<div class="forgot-pw-link">
     <a href="{% url "user:password_reset" %}">forgot your username/password?</a>
</div>
{% endblock %}

<script>
  document.getElementById("id_username").focus();
</script>

server/apps/user_management/templates/user_management/password_reset_complete.html
{% extends "base_form.html" %}

{% block main %}
<div class="sole-content">
<p>
 You should receive a password-reset email shortly
</p>
<p> 
 (check your spam folder if you don't see anything)
</p>
</div>
{% endblock %}

server/apps/user_management/templates/user_management/password_reset_confirm.html
{% extends "base_form.html" %}

{% block headtitle %}Metacademy Password Reset{% endblock %}

{% block form-content%}
{% if validlink %}
<div class="user-form-field">
  {{ form.new_password1.label_tag }}
  {{ form.new_password1 }}
  {% if form.new_password1.errors %}
  <div class="form-errors">
    {{form.new_password1.errors}}
  </div>
  {% endif %}
</div>

<div class="user-form-field">
  {{ form.new_password2.label_tag }}
  {{ form.new_password2 }}
  {% if form.new_password2.errors %}
  <div class="form-errors">
    {{form.new_password2.errors}}
  </div>
  {% endif %}
</div>



{% else %}

<p>The password reset link was invalid, possibly because it has already been used. Please <a href="{% url "user:password_reset" %}">request a new password reset</a>.</p>

{% endif %}

{% block submit-button %}
<div class="submit-field" {% if not validlink %}style="display: none;"{% endif %}>
  <input type="submit" value={% block button-text %}"change password"{% endblock %} />
</div>
{% endblock %}

{% endblock %}

server/apps/user_management/templates/user_management/password_reset_done.html
{% extends "base_form.html" %}

{% block main %}
<div class="sole-content">
<p>
 Your password reset was successful
</p>
<p> 
  you may now <a class="internal-link" href="/user">login</a>.
</p>
</div>
{% endblock %}

server/apps/user_management/templates/user_management/password_reset_email.html
Hello,

Someone requested a password reset for your metacademy.org account with username:

{{user}}

If you initiated this request, please go to the following page and choose a new password:

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url "user:password_reset_confirm" uidb64=uid token=token %}
{% endblock %}

best wishes,

the Metacademy team

server/apps/user_management/templates/user_management/password_reset_form.html
{% extends "base_form.html" %}

{% block headtitle %}Metacademy Password Reset{% endblock %}

{% block formaction %}
"{% url django.contrib.auth.views.password_reset %}"
{% endblock %}

{% block form-content %}
<div class="user-form-field">
  <label for="email-input"> Please enter your email:</label>
  <input type="email" name="email" id="email-input">
  {% if form.email.errors %}
    <div class="form-errors">
      {{form.email.errors}}
    </div>
  {% endif %}

</div>
{% endblock %}

{% block button-text %}"Send password-reset email"{% endblock %}

server/apps/user_management/templates/user_management/register.html
{% extends "user_management/login.html" %}

{% block headtitle %} Metacademy Registration {% endblock %}

{% block form-content %}
<div class="user-form-field">
  {{ form.username.label_tag }}
  {{ form.username }}
  {% if form.username.errors %}
  <div class="form-errors">
    {{form.username.errors}}
  </div>
  {% endif %}
</div>

<div class="user-form-field">
  {{ form.email.label_tag }}
  {{ form.email }}
  {% if form.email.errors %}
  <div class="form-errors">
    {{form.email.errors}}
  </div>
  {% endif %}

</div>

<div class="user-form-field">
  {{ form.password1.label_tag }}
  {{ form.password1 }}
  {% if form.password1.errors %}
  <div class="form-errors">
    {{form.password1.errors}}
  </div>
  {% endif %}

</div>

<div class="user-form-field">
  {{ form.password2.label_tag }}
  {{ form.password2 }}
  {% if form.password2.errors %}
  <div class="form-errors">
    {{form.password2.errors}}
  </div>
  {% endif %}
</div>

<div class="user-form-field">
  <label for="id_password2">I agree to the <a target="_blank" href="/terms" class="internal-link">Terms of Use</a>:</label>
  {{ form.tou }}
  {% if form.tou.errors %}
  <div class="form-errors">
    {{form.tou.errors}}
  </div>
  {% endif %}
</div>

<div class="user-form-field">
  <label for="id_captcha_1"> Solve this problem</label>
  <div class="captcha-wrapper">
    {{ form.captcha }}
  </div>
  {% if form.captcha.errors %}
  <div class="form-errors">
    {{form.captcha.errors}}
  </div>
  {% endif %}

</div>

{% endblock %}    

{% block button-text %}"create account"{% endblock %}

server/apps/user_management/templates/user_management/user.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra-css %}
<link rel="stylesheet" href="{% static "css/userpage.css" %}"/>
{% endblock %}

{% block main %}
<div class="user-profile">
  <h1>
    {{user.username}}
  </h1>
  <hr>

  <section id="account-section">
    <h2>
      Your Account
    </h2>
    <div class="user-account-info user-subsec">
      <ul>
        <li> username (public): {{user.username}}</li>
        <li> email (not public): {{user.email}}</li>
      </ul>
    </div>
  </section>

  <section id="graphs-section">
    <h2>
      Graphs You've Created/Edited
    </h2>
    <div class="user-graphs list-wrapper user-subsec">
    {% if graphs %}
    {% for entry in graphs %}
    <li class="list-roadmaps-li">
      <h3 class="list-roadmaps-title">
        <a class="list-roadmaps-link internal-link" href="{{ entry.graphsettings.get_absolute_url }}"> {{ entry.title }} </a>
      </h3>
    </li>
    {% endfor %}
    {% else %}
      <span class="no-content-message"> you have not yet created any graphs</span>
    {% endif %}
    </div>
  </section>

  <section id="contribs-section">
    <h2>
      Your Roadmaps
    </h2>
    <div class="user-graphs list-wrapper user-subsec">
    {% if roadmaps %}
    {% for entry in roadmaps %}
    <li class="list-roadmaps-li">
      <h3 class="list-roadmaps-title">
        <a class="list-roadmaps-link internal-link" href="{{ entry.roadmapsettings.get_absolute_url }}"> {{ entry.title }} </a>
      </h3>
    </li>
    {% endfor %}
    {% else %}
      <span class="no-content-message"> you have not yet created any roadmaps</span>
    {% endif %}
    </div>
  </section>

  <section id="graphs-section">
    <h2>
      Concepts You've Created/Edited
    </h2>
    <div class="user-graphs list-wrapper user-subsec">
    {% if concepts %}
    {% for entry in concepts %}
    <li class="list-roadmaps-li">
      <h3 class="list-roadmaps-title">
        <a class="list-roadmaps-link internal-link" href="{{ entry.conceptsettings.get_absolute_url }}"> {{ entry.title }} </a>
      </h3>
    </li>
    {% endfor %}
    {% else %}
      <span class="no-content-message"> you have not yet created any concepts</span>
    {% endif %}
    </div>
  </section>

  <section id="lc-section">
    <h2>
      Your Starred Concepts
    </h2>
    <div class="starred-concepts list-wrapper user-subsec">
      {% if sconcepts %}
      <ul>
        {% for entry in sconcepts %}
        <li class="list-concepts-li">
          <h3 class="list-concepts-title">
            <a class="list-concepts-link internal-link" href="{% url 'graphs:concepts' entry.tag %}"> {{ entry.title }} </a>
          </h3>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <span class="no-content-message"> you have not yet starred any concepts on metacademy </span>
      {% endif %}
    </div>
  </section>

  <section id="lc-section">
    <h2>
      Your Learned Concepts
    </h2>
    <div class="learned-concepts list-wrapper user-subsec">
      {% if lconcepts %}
      <ul>
        {% for entry in lconcepts %}
        <li class="list-concepts-li">
          <h3 class="list-concepts-title">
            <a class="list-concepts-link internal-link" href="{% url 'graphs:concepts' entry.tag %}"> {{ entry.title }} </a>
          </h3>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <span class="no-content-message"> you have not yet learned any concepts on metacademy </span>
      {% endif %}
    </div>
  </section>

</div>
{% endblock %}