backend/urls.py
from django.conf.urls import patterns, include, url
# handle static files locally
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import cache_page
from backend.views import get_kmap_browser_view, get_search_view, get_landing_page

"""
Django urls handler. Valid URLS/Requests:
  kmap(s)                           display knowledge-map browser

see backend/simple_server for valid content requests
"""

urlpatterns = patterns('',
                       (r'^$', get_landing_page),
                       (r'^(?i)kmaps?/', get_kmap_browser_view),
                       (r'^(?i)search', get_search_view)
)

urlpatterns += staticfiles_urlpatterns()

server/apps/roadmaps/urls.py
from django.conf.urls import patterns, url

from apps.roadmaps import views

urlpatterns = patterns('',
                       url(r'^$', views.list),
                       url(r'^preview$', views.preview, name='preview'),
                       url(r'^new$', views.new, name='new'),
                       url(r'^([^/]+)/([^/]+)$', views.show, name='show'),
                       url(r'^([^/]+)/([^/]+)/edit$', views.edit, name='edit'),
                       url(r'^([^/]+)/([^/]+)/history$', views.show_history, name='history'),
                       url(r'^([^/]+)/([^/]+)/settings$', views.settings, name='settings'),
                       url(r'^([^/]+)/([^/]+)/version/(\d+)$', views.show, name='version'),
                       url(r'^([^/]+)/([^/]+)/version/(\d+)/changes$', views.show_changes, name='changes'),
                       url(r'^([^/]+)/([^/]+)/update_to_revision/(\d+)$', views.update_to_revision, name='revert'),
                       url(r'^([^/]+)$', views.list_by_user, name='user-list'),
                       )

server/urls.py
import pdb
from django.conf.urls import patterns, include, url
# handle static files locally
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView, RedirectView
from haystack.views import search_view_factory
from haystack.query import SearchQuerySet

from apps.roadmaps import views as roadmap_views

from views import MultiSearchView, ContactView, get_list_view, get_browsing_view, autocomplete

admin.autodiscover()

sqs = SearchQuerySet().filter(is_listed_in_main_str="True")
sqs.order_by('score')
search_inst = search_view_factory(view_class=MultiSearchView, searchqueryset=sqs, template='search-results.html')

"""
Django urls handler
"""
urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(template_name="landing.html")),
                       url(r'^(?i)autocomplete/?$', autocomplete, name="autocomplete"),
                       url(r'^(?i)search$', search_inst, name="haystack_search"),
                       url(r'^(?i)list$', get_list_view),
                       url(r'^(?i)browse$', get_browsing_view),
                       url(r'^(?i)concepts/((?P<anything>.*))',
                           RedirectView.as_view(url="/graphs/concepts/%(anything)s", query_string=True), name='concepts'),
                       url(r'^(?i)graphs/', include('apps.graph.urls', namespace="graphs") ),
                       url(r'^user/', include('apps.user_management.urls', namespace='user') ),
                       url(r'^roadmaps/', include('apps.roadmaps.urls', namespace='roadmaps')),
                       url(r'^course_guides/', roadmap_views.course_guide_list),
                       url(r'^captcha/', include('captcha.urls')),
                       url(r'^about/?$', TemplateView.as_view(template_name='about.html')),
                       url(r'^terms/?$', TemplateView.as_view(template_name='terms_of_service.html'), name="terms"),
                       url(r'^feedback/?$', ContactView.as_view()),
                       url(r'^thanks/?$', TemplateView.as_view(template_name='feedback_thanks.html')),
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^browser-tests', include('apps.browser_tests.urls', namespace="btests")),
)

urlpatterns += staticfiles_urlpatterns()

server/apps/roadmaps/forms.py
import pdb
import os

from django.forms import ModelForm, Textarea, CharField, TextInput

import models

PLACEHOLDER_TXT = 'Optional: write a brief message explaining your change'

class RoadmapForm(ModelForm):
    commit_msg = CharField( max_length=200, required=False, widget=TextInput(attrs={'placeholder': PLACEHOLDER_TXT}))
    class Meta:
        model = models.Roadmap
        fields = ('body', 'title', 'author', 'audience', 'blurb')
        widgets = {
            'body': Textarea(attrs={'rows': 40, 'maxlength': 200000}),
            'title': TextInput(attrs={'placeholder': 'Title for your roadmap'}),
            'author': TextInput(attrs={'placeholder': 'Separate authors with a comma'}),
            'audience': TextInput(attrs={'placeholder': 'Who do you want to read this roadmap?'}),
            'blurb': Textarea(attrs={'placeholder': 'briefly describe this roadmap -- this text is currently used for searching'}),
            }

    def clean(self):
        cleaned_data = super(RoadmapForm, self).clean()
        if (not cleaned_data.has_key('commit_msg')) or cleaned_data['commit_msg'] == PLACEHOLDER_TXT:
           cleaned_data['commit_msg'] = ''
        return cleaned_data

class RoadmapSettingsForm(ModelForm):
    class Meta:
        model = models.RoadmapSettings
        fields = ('doc_type', 'listed_in_main', 'url_tag', 'sudo_listed_in_main', 'anyone_can_edit')

server/apps/roadmaps/views.py
import difflib
import os
from operator import attrgetter

import bleach
import markdown
import re
import urlparse
import reversion
from lazysignup.templatetags.lazysignup_tags import is_lazy_user

from django.db import transaction
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils import safestring
from django.utils.html import escape
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse

from apps.graph.models import Concept
from utils.roadmap_extension import RoadmapExtension
from utils.mathjax_extension import MathJaxExtension
from forms import RoadmapForm, RoadmapSettingsForm
import models


BLEACH_TAG_WHITELIST = ['a', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul',
                        'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'div', 'pre',
                        'table', 'tr', 'th', 'tbody', 'thead', 'td', 'img', 'div']
BLEACH_ATTR_WHITELIST = {
    '*': ['id', 'class'],
    'a': ['href', 'rel'],
    'img': ['src', 'alt', 'width', 'height']
}


# TODO what is this used for - Colorado
def metacademy_domains():
    return ['']


def is_internal_link(url):
    p = urlparse.urlparse(url)
    if p.netloc not in metacademy_domains():
        return False
    return p.path.find('/concepts/') != -1


re_tag = re.compile(r'/concepts/(\w+)')
def parse_tag(url):
    m = re_tag.match(url)
    if m:
        return m.group(1)
    else:
        return None


def process_link(attrs, new=False):
    if is_internal_link(attrs['href']):
        if Concept.objects.filter(tag=parse_tag(attrs['href'])).exists():
            attrs['class'] = 'internal-link'
        else:
            attrs['class'] = 'internal-link missing-link'
    else:
        attrs['class'] = 'external-link'
    attrs['target'] = '_blank'
    return attrs


def wiki_link_url_builder(label, base, end):
    """
    TODO allow tags and titles (how to distinguish?)
    """
    res = Concept.objects.filter(title=label)
    if len(res):
        return base + res[0].tag
    else:
        return base + label


def markdown_to_html(markdown_text):
    """
    converts markdown text to html using the markdown python library
    """
    roadmap_ext = RoadmapExtension()
    mathjax_ext = MathJaxExtension()
    body_html = markdown.markdown(markdown_text,
                                  extensions=[roadmap_ext, mathjax_ext, 'toc', 'sane_lists', 'extra', 'wikilinks(base_url=/concepts/)'],
                                  extension_configs={'wikilinks(base_url=/concepts/)': [('build_url', wiki_link_url_builder)]})
    html = bleach.clean(body_html, tags=BLEACH_TAG_WHITELIST, attributes=BLEACH_ATTR_WHITELIST)
    return bleach.linkify(html, callbacks=[process_link])


def show(request, in_username, tag, vnum=-1):
    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)

    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    if not roadmap_settings.viewable_by(request.user):
        return HttpResponse(status=404)

    vnum = int(vnum)
    versions = _get_versions_obj(roadmap)
    num_versions = len(versions)

    if num_versions > vnum >= 0:
        roadmap = versions[vnum].object_version.object

    common_rm_dict = get_common_roadmap_dict(roadmap, roadmap_settings, request.user, in_username, tag)

    return render(request, 'roadmap.html', dict({
        'body_html': markdown_to_html(roadmap.body),
        'num_versions': num_versions,
        'page_class': "view"
    }, **common_rm_dict))


def format_diff_line(line):
    line = escape(line)
    if line[0] == '+':
        return '<ins>' + line + '</ins>'
    elif line[0] == '-':
        return '<del>' + line + '</del>'
    else:
        return line


def show_changes(request, in_username, tag, vnum=-1):
    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)

    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    if not roadmap_settings.viewable_by(request.user):
        return HttpResponse(status=404)

    vnum = int(vnum)
    versions = _get_versions_obj(roadmap)
    num_versions = len(versions)

    if num_versions > vnum >= 0:
        roadmap = versions[vnum].object_version.object

    curr_body = roadmap.body
    curr_lines = curr_body.splitlines()

    if vnum > 0:
        prev_roadmap = versions[vnum - 1].object_version.object
        prev_body = prev_roadmap.body
    else:
        prev_body = ''
    prev_lines = prev_body.splitlines()

    differ = difflib.Differ()
    diff_lines = differ.compare(prev_lines, curr_lines)
    diff_lines = filter(lambda l: l[0] != '?', diff_lines)
    diff = '\n'.join(map(format_diff_line, diff_lines))

    common_rm_dict = get_common_roadmap_dict(roadmap, roadmap_settings, request.user, in_username, tag)

    return render(request, 'roadmap-diff.html', dict({
        'diff': diff,
    }, **common_rm_dict))


def show_history(request, in_username, tag):
    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)
    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    if not roadmap_settings.viewable_by(request.user):
        return HttpResponse(status=404)

    cur_version_num = roadmap.version_num

    revs = _get_versions_obj(roadmap)[::-1]
    common_rm_dict = get_common_roadmap_dict(roadmap, roadmap_settings, request.user, in_username, tag)
    return render(request, 'roadmap-history.html',
                  dict({"revs": revs,
                        'page_class': "history",
                        'cur_version_num': cur_version_num,
                        'show_change_button': True,
                        'show_preview_button': True
                        }, **common_rm_dict))


@csrf_exempt
def update_to_revision(request, in_username, tag, vnum):
    """
    update the given roadmap to the specified reversion number (simply copies over the previous entry)
    """
    if not request.method == "PUT":
        return HttpResponse(status=403)

    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)

    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    can_edit = roadmap_settings.editable_by(request.user)
    if not can_edit:
        return HttpResponse(status=401)

    vnum = int(vnum)
    versions = _get_versions_obj(roadmap)
    num_versions = len(versions)

    if 0 > vnum or vnum >= num_versions:
        return HttpResponse(status=404)
    versions[vnum].revision.revert()

    return HttpResponse(status=200)


def _get_versions_obj(obj):
    return reversion.get_for_object(obj).order_by("id")


@transaction.atomic
def edit(request, in_username, tag):
    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)

    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    if not roadmap_settings.viewable_by(request.user):
        return HttpResponse(status=404)

    common_rm_dict = get_common_roadmap_dict(roadmap, roadmap_settings, request.user, in_username, tag)

    can_edit = roadmap_settings.editable_by(request.user)

    if request.method == 'POST':
        if not (request.user.is_authenticated() and can_edit):
            # TODO inform the user that they cannot edit
            return HttpResponse(status=401)

        form = RoadmapForm(request.POST, instance=roadmap)

        if form.is_valid():
            versions = _get_versions_obj(roadmap)
            cur_vn = len(versions) + 1
            smodel = form.save(commit=False)
            smodel.version_num = cur_vn
            with reversion.create_revision():
                smodel.save()
                reversion.set_user(request.user)
                reversion.set_comment(form.cleaned_data['commit_msg'])

            if request.POST["submitbutton"] == "Publish" and common_rm_dict['can_change_settings']:
                roadmap_settings.published = True
                roadmap_settings.save()
                return HttpResponseRedirect('/roadmaps/%s/%s' % (in_username, tag))

    elif request.method == 'GET':
        form = RoadmapForm(instance=roadmap)
    else:
        return HttpResponse(status=403)

    return render(request, 'roadmap-edit.html', dict({
        'form': form,
        'page_class': "edit",
    }, **common_rm_dict))


def settings(request, in_username, tag):
    # check that the user is logged in
    if not request.user.is_authenticated() or is_lazy_user(request.user):
        return HttpResponseRedirect(reverse("user:login"))

    # get the roadmap and settings
    try:
        rm_dict = get_roadmap_objs(in_username, tag)
    except:
        return HttpResponse(status=404)
    roadmap = rm_dict["roadmap"]
    roadmap_settings = rm_dict["settings"]

    # make sure the user is capable of changing the settings
    if (not roadmap_settings.can_change_settings(request.user)):
        return HttpResponse(status=401)

    if request.method == 'POST':
        form = RoadmapSettingsForm(request.POST, instance=roadmap_settings)
        rms_sudo_listed_in_main = roadmap_settings.sudo_listed_in_main
        if form.is_valid():
            rs = form.save(commit=False)
            if not request.user.is_superuser:
                rs.sudo_listed_in_main = rms_sudo_listed_in_main
            rs.save()

            return HttpResponseRedirect('/roadmaps/%s/%s' % (in_username, form.data['url_tag']))
    elif request.method == 'GET':
        form = RoadmapSettingsForm(instance=roadmap_settings)
    else:
        return HttpResponse(status=403)

    common_rm_dict = get_common_roadmap_dict(roadmap, roadmap_settings, request.user, in_username, tag)

    return render(request, 'roadmap-settings.html', dict({
        'settings_form': form,

server/apps/roadmaps/templates/roadmap-base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Metacademy - {{ roadmap.title|escape }}
{% endblock %}

{% block extra-css %}
<link rel="stylesheet" href="{% static "css/roadmap.css" %}"> </link>
{% endblock %}

{% block main %}
{% block roadmap-header %}
<div class="roadmap-header {{ page_class }}">
  <h1>
  {% block roadmap-title %}
  {{ roadmap.title }}
  {% endblock %}
  </h1>

  {% block roadmap-nav %}
  <div class="roadmap-header-nav" class="{{page_class}}">
    <a href="{{ base_url }}" id="read-nav">Read</a>
    <a href="{{ edit_url }}" id="source-nav">View source</a>
    <a href="{{ history_url }}" id="history-nav">View history</a>
    {% if can_change_settings %}
      <a href="{{ settings_url }}" id="settings-nav">Settings</a>
    {% endif %}
  </div>
  {% endblock %}
</div>
{% endblock %}

{% block roadmap-content %}

{% endblock %}

{% endblock %}

server/apps/roadmaps/templates/roadmap-content.html
{% if not is_published %}
  <div class="roadmap-alert">
    This roadmap is not published and is only viewable by those on the editor list.
  </div>
{% endif %}

<div class="aux-info">
  <div class="author"> Created by: {{ roadmap.author }} </div>
  <div class="audience"> Intended for: {{ roadmap.audience }} </div>
</div>
<div class="content"> {{ body_html|safe }} </div>

<script type="text/javascript"
  src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

server/apps/roadmaps/templates/roadmap-diff.html
<pre class="roadmap-diff">
{{ diff|safe }}
</pre>
  

server/apps/roadmaps/templates/roadmap-edit.html
{% extends "roadmap-base.html" %}
{% load staticfiles %}

{% block extra-css %}
<link rel="stylesheet" href="{% static "css/roadmap.css" %}" />
<link rel="stylesheet" href="{% static "css/lib/colorbox.css" %}" media="screen" />
<link rel="stylesheet" href="{% static "css/roadmap-markdown-editor.css" %}" />
<link rel="stylesheet" href="{% static "css/form-errors.css" %}"> </link>
<style>
  .form-errors, .non-field-form-errors{
    width: 20%;
    margin: 0.5em 0 0 25%;
  }
</style>
{% endblock %}

{% block jscript-extend %}
<script src="{% static "javascript/lib/jquery.colorbox-min.js" %}"></script>
<script src="{% static "javascript/roadmap-markdown-editor.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/roadmap-edit.js" %}"></script>
{% endblock %}

{% block roadmap-content %}

<div class="form-wrapper">
  {% if not can_edit %}
  <div class="no-edit-inform">
    Note: your changes to this roadmap will not be saved (you're not on the editor list),
  </div>
  {% endif %}

  <form method="post" action="">

    {% if form.non_field_errors %}
    <div class="non-field-form-errors">
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
    </div>
    {% endif %}

    {% csrf_token %}

    {% block form-content %}

	  <div class="form-field">
	    {{ form.title.label_tag }}
	    {{ form.title }}
      {% if form.title.errors %}
      <div class="form-errors">
        {{form.title.errors}}
      </div>
      {% endif %}
	  </div>

	  <div class="form-field">
	    {{ form.author.label_tag }}
	    {{ form.author }}
      {% if form.author.errors %}
      <div class="form-errors">
        {{form.author.errors}}
      </div>
      {% endif %}
	  </div>

    <div class="form-field">
      {{ form.audience.label_tag }}
      {{ form.audience }}
      {% if  form.audience.errors  %}
      <div class="form-errors">
        {{ form.audience.errors }}
      </div>
      {% endif %}
    </div>

    <div class="form-field">
      <label for="id_blurb">Quick Description:</label>
      {{ form.blurb }}
      {% if  form.blurb.errors  %}
      <div class="form-errors">
        {{ form.blurb.errors }}
      </div>
      {% endif %}
    </div>

    {% block settings-form %}
    {% include "settings-form-tidbit.html" %}
    {% endblock %}

    <div class="body-button-wrapper">
      <div class="form-body">
        {{ form.body }}
        {% if  form.body.errors  %}
        <div class="form-errors">
          {{ form.body.errors }}
        </div>
        {% endif %}
      </div>
      {% if can_edit %}
      <div id="edit-summary" class="form-field">
        <label for="commit-blurb">Edit Message</label>
        {{ form.commit_msg }}
        {% if  form.commit_msg.errors  %}
        <div class="form-errors">
          {{ form.commit_msg.errors }}
        </div>
        {% endif %}
      </div>
      {% endif %}
      <div class="buttons">
        <button id="preview-button" class="submit-button"> Preview </button>
        {% if can_edit %}
        <input id="save-button" class="submit-button" name="submitbutton" type="submit" value="Save"/>
          {% if not is_published %}
          <input id="publish-button" class="submit-button" name="submitbutton" type="submit" value="Publish"/>
          {% endif %}
        {% endif %}
      </div>
    </div>

    {% endblock %}

  </form>
</div>



{% endblock %}

server/apps/roadmaps/templates/roadmap-history.html
{% extends "roadmap-base.html" %}
{% load staticfiles %}

{% block extra-css %}
<link rel="stylesheet" href="{% static "css/roadmap.css" %}"> </rel>
<link rel="stylesheet" href="{% static "css/lib/colorbox.css" %}" media="screen" />
<link rel="stylesheet" href="{% static "css/reversions.css" %}"> </link>
{% endblock %}

{% block jscript-extend %}
<script src="{% static "javascript/lib/jquery.colorbox-min.js" %}"></script>
<script src="{% static "javascript/roadmap-history.js" %}"></script>
{% endblock %}

{% block roadmap-content %}
  {% include "reversions.html" %}
{% endblock %}

server/apps/roadmaps/templates/roadmap-list.html
{% extends "base.html" %}
{% load staticfiles $}
{% load static %}


{% block jscript-extend %}
<script type="text/javascript" src="{% static "javascript/gen-utils.js" %}"></script>
{% endblock %}

{% block title %}
  Metacademy - {{ pl_doc_type }}
{% endblock %}

{% block extra-css %}
  <link rel="stylesheet" href="{% static "css/search.css" %}" />
{% endblock %}


{% block main %}
  <div class="search-res-wrapper">

    <h1>
      Public {{ pl_doc_type }}
      <a id="new-roadmap-link" href="{% url 'roadmaps:new' %}">+ New {{ doc_type }}</a>
    </h1>

    <div class="search-res">
      {% if not roadmaps|length %}
        <div class="nosearch-message">
          {{ empty_message }}
        </div>
      {% endif %}
      <ul class="search-res-list">
        {% for roadmap in roadmaps %}
          <li class="search-res-li">
            <h3 class="search-res-title">
              <a class="search-res-link internal-link" href="{{ roadmap.roadmapsettings.get_absolute_url }}"> {{ roadmap.title }} </a>
            </h3>
            <div class="search-res-description">
              <p>Created by: {{ roadmap.author }}</p>
              <p>Intended for: {{ roadmap.audience }}</p>
              <p>{{ roadmap.blurb }}</p>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>

  </div>
{% endblock %}

server/apps/roadmaps/templates/roadmap-new.html
{% extends "roadmap-edit.html" %}

{% block roadmap-title %}New roadmap{% endblock %}

{% block roadmap-nav %}
{% endblock %}

server/apps/roadmaps/templates/roadmap-settings.html
{% extends "roadmap-edit.html" %}
{% load staticfiles %}

{% block extra-css %}
<link rel="stylesheet" href="{% static "css/roadmap.css" %}" />
<!-- TODO hack -->
<style>
.buttons {
text-align: right;
  margin-right: 12.5em;
}
</style>
{% endblock %}

{% block jscript-extend %}
{% endblock %}

{% block form-content %}
{% include "settings-form-tidbit.html" %}
<div class="buttons">
  <input id="submit-button" type="submit" value="{% block form-submit-button-value %}Save{% endblock %}" class="submit-button onclick="this.disabled = true; this.form.submit();"/>
</div>
<div class="dev-note">
  <p>
    Additional settings options will be made available here soon (e.g. adding additional editors).
  </p>
  <p>
    <a href="http://metacademy.org/feedback">Contact us</a> if you'd like to see any additional functionality here.
  </p>
</div>
{% endblock %}

server/apps/roadmaps/templates/roadmap.html
{% extends "roadmap-base.html" %}


{% block roadmap-content %}

<div class="container">
  {% include "roadmap-content.html" %}
</div>

{% endblock %}

server/apps/roadmaps/templates/settings-form-tidbit.html
<div id="settings-form">
  <div class="form-field">
    {{ settings_form.url_tag.label_tag }}
    {{ settings_form.url_tag }}
    {% if settings_form.url_tag.errors  %}
    <div class="form-errors">
      {{ settings_form.url_tag.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-field">
    {{ settings_form.doc_type.label_tag }}
    {{ settings_form.doc_type }}
    {% if settings_form.doc_type.errors  %}
    <div class="form-errors">
      {{ settings_form.doc_type.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-field">
    {{ settings_form.owners.label_tag }}
    {{ settings_form.owners }}
    {% if settings_form.owners.errors  %}
    <div class="form-errors">
      {{ settings_form.owners.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-field">
    {{ settings_form.anyone_can_edit.label_tag }}
    {{ settings_form.anyone_can_edit }}
    {% if settings_form.anyone_can_edit.errors  %}
    <div class="form-errors">
      {{ settings_form.editors.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-field">
    {{ settings_form.editors.label_tag }}
    {{ settings_form.editors }}
    {% if settings_form.editors.errors  %}
    <div class="form-errors">
      {{ settings_form.editors.errors }}
    </div>
    {% endif %}
  </div>
  <div class="form-field">
    {{ settings_form.listed_in_main.label_tag }}
    {{ settings_form.listed_in_main }}
    {% if settings_form.listed_in_main.errors  %}
    <div class="form-errors">
      {{ settings_form.listed_in_main.errors }}
    </div>
    {% endif %}
  </div>
  {% if user.is_superuser %}
  <div class="form-field">
    {{ settings_form.sudo_listed_in_main.label_tag }}
    {{ settings_form.sudo_listed_in_main }}
    {% if settings_form.sudo_listed_in_main.errors  %}
    <div class="form-errors">
      {{ settings_form.sudo_listed_in_main.errors }}
    </div>
    {% endif %}
  </div>
  {% endif %}

</div>